Port: "8080"
Log:
    LogPath: "./latest.log"
    CLS:
        Endpoint: ""
        AccessKey: ""
        AccessToken: ""
        TopicID: ""
SentryDsn: ""
B2:
    BucketKeyID: ""
    BucketKey: ""
    BucketName: ""
MySQL:
    Addr: "localhost"
    Port: "3306"
    User: "root"
    Password: "123456"
    Database: "jframe"
    UseTLS: false
    Debug: false
Pyroscope:
    ApplicationName: ""
    ServerAddress: ""
    BasicAuthUser: ""
    BasicAuthPass: ""
    TenantID: ""
Redis:
    Addr: "localhost"
    Port: "6379"
    Password: ""
    Db: 0
Uptrace:
    ServiceName: ""
    ServiceVersion: ""
    DSN: ""
